# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efaeac9025a87b54ea81a5c3d45e2e508a58192d66c820f4c25bec5d6cb3ec2d5f4d5881651ceb7126dc889689c1ecce504d173f40bd5b785e5370367208d8ae

test:
  secret_key_base: e9a5d51c6c9a2619eb87666c21190ed724a7c81642c2eaf1786461e882ec62c30e6df168fce219be5d267255dc75d19632e72d97d8e50480e3527bd7318155ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
